ego:
  fastdfs:
    nginx: http://192.168.8.129:8888/
  bigad:
    categoryId: 89
  redis:
    bigad:
      cacheName: com.ego.portal
      key: bigad
  rabbitmq:
    content:
      queuename: content
    item:
      insertName: insertItem
      deleteName: deleteItem
    order:
      createOrder: createOrder
      deleteCart: deleteCart
    mail: mail


  portal:
    location: http://localhost:8082/
  search:
    location: http://localhost:8083/
  item:
    redisKey: 'com.ego.item::showItem:'
  cart:
    tempcart: tempcart
    redisKey: 'cart:'
    location: http://localhost:8085/
  passport:
    loginurl: http://localhost:8084/user/showLogin
