ego:
  fastdfs:
    nginx: http://192.168.8.129:8888/
  bigad:
    categoryId: 89
  redis:
    bigad:
      cacheName: com.ego.portal
      key: bigad
  rabbitmq:
    content:
      queuename: content