# dubbo的consumer方，配置zk位置
dubbo:
  application:
    name: ego-manage
  registry:
    address: zookeeper://192.168.8.128:2181
# web项目，配置端口
server:
  port: 80

#Spring MVC视图解析器
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # 引入commons和rabbitmq，加载其配置文件
  profiles:
    active: commons,rabbitmq